### ISSUE TITLE
nil value (field 'lastname')

### ISSUE THREAD

**Issue by argykaraz** [Gregory-Hepicloud/stats_esx#1]
As the title says, the error I am getting is:
client/cl_stats/lua:42 attempt to concatenate a nil value (field 'lastname)

I have esx_policejob started.

**Comment by Gregory-Hepicloud** [comment]
do you have esx identity ? if yes do you have enable in police job ?

Config.EnableESXIdentity          = true -- Enable if you're using esx_identity. (police job config)

**Comment by argykaraz** [comment]
I do have esx_identity and also enabled it in policejob.
Is there a specific order that the resources have to be started? For example do I have to have stats_esx BEFORE or AFTER police job?
What I am currently doing, is have the server started, and I manually start the Stats.

**Comment by Gregory-Hepicloud** [comment]
ensure mysql-async 1
ensure esx_identity 2 
ensure esx_policejob 3
ensure esx_stats 4

**Comment by argykaraz** [comment]
This is the order I am having. Still the problem is the same.
I just removed the lastname to see what it does, and now I am getting errors in my server.

`SCRIPT ERROR: @Stats/server/sv_stats.lua:31: attempt to index a nil value (global 'MySQL')`

So I added this at fxmanifest.lua
```
server_scripts {
		'@mysql-async/lib/MySQL.lua',
    'server/sv_stats.lua' 
}

```

I am now getting database writes, but the only fields being written, are:
Name (only the First name, since I deleted the Last name), SourceID and date_recorded. The rest are empty.

**Comment by Gregory-Hepicloud** [comment]
Update github for the 'attempt to index a nil value (global 'MySQL')' thx

but for other information it's weird because it is retrieved directly in esx 😅

what is your esx version ?

**Comment by argykaraz** [comment]
This is my esx version:
https://github.com/esx-framework/es_extended/tree/v1-final

**Comment by Gregory-Hepicloud** [comment]
suddenly I do not know where the problem comes from because I have everything like you and at home it works

**Comment by argykaraz** [comment]
I even downloaded identity and policejob from the links you provided and still the same problem.

if it helps here is my server console:
`[MariaDB:10.3.25-MariaDB-0+deb10u1] [stats_esx] [12ms] INSERT INTO stats (`Name`, `SourceID`, `FirstLast`, `Citizenid`, `MoneyTotal`, `Job`, `JobLabel`, `OnDuty`) VALUES ('argykaraz', 'steam:sensitiveinfo', @FirstLast, @Citizenid, @MoneyTotal, @Job, @JobLabel, @OnDuty)`

**Comment by Gregory-Hepicloud** [comment]
Go to client and line 30 add : `dump(PlayerData)` and give me log from console ingame
and to server after line 8 :
```
    print(Name)
    print(FirstLast)
    print(Citizenid)
    print(MoneyTotal)
    print(Job)
    print(JobLabel)
    print(OnDuty)
```
and same give me the log

**Comment by argykaraz** [comment]
from the server when restarted the resource
```
Creating script environments for stats_esx
nil
nil
nil
nil
nil
nil
nil
Started resource stats_esx
```

the script is not starting:
Error loading script client/cl_stats.lua in resource stats_esx: @stats_esx/client/cl_stats.lua"30: attempt to call a nil value (global 'dump')
stack traceback:
@stats_esx/client/cl_stats.lua:30 in main chunk

**Comment by Gregory-Hepicloud** [comment]
unfortunately I do not see where the problem comes from because if he does not find the dump there is a problem with you because at home I tried with another server and everything worked
